//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mapper.Communication.Entities {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResEntities {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResEntities() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mapper.Communication.Entities.ResEntities", typeof(ResEntities).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ativo.
        /// </summary>
        public static string ActiveDAO {
            get {
                return ResourceManager.GetString("ActiveDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa Mãe.
        /// </summary>
        public static string boardCOMPUTER {
            get {
                return ResourceManager.GetString("boardCOMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gabinete.
        /// </summary>
        public static string CabinetDESK {
            get {
                return ResourceManager.GetString("CabinetDESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cooler do Processador.
        /// </summary>
        public static string CoolerDESK {
            get {
                return ResourceManager.GetString("CoolerDESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Processador.
        /// </summary>
        public static string CpuCOMPUTER {
            get {
                return ResourceManager.GetString("CpuCOMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criado em.
        /// </summary>
        public static string CreateDAO {
            get {
                return ResourceManager.GetString("CreateDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Veontoinhas.
        /// </summary>
        public static string FanDESK {
            get {
                return ResourceManager.GetString("FanDESK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fonte de Alimentação.
        /// </summary>
        public static string FonteCOMPUTER {
            get {
                return ResourceManager.GetString("FonteCOMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Placa de Vídeo.
        /// </summary>
        public static string GpuCOMPUTER {
            get {
                return ResourceManager.GetString("GpuCOMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ID.
        /// </summary>
        public static string IdDAO {
            get {
                return ResourceManager.GetString("IdDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fabricante.
        /// </summary>
        public static string ManufactoryNOTE {
            get {
                return ResourceManager.GetString("ManufactoryNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Modelo.
        /// </summary>
        public static string ModelNOTE {
            get {
                return ResourceManager.GetString("ModelNOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Observação.
        /// </summary>
        public static string ObservationDAO {
            get {
                return ResourceManager.GetString("ObservationDAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Memória RAM.
        /// </summary>
        public static string RamCOMPUTER {
            get {
                return ResourceManager.GetString("RamCOMPUTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Armazenamento.
        /// </summary>
        public static string StorageComputer {
            get {
                return ResourceManager.GetString("StorageComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Atualizado em.
        /// </summary>
        public static string UpdateDAO {
            get {
                return ResourceManager.GetString("UpdateDAO", resourceCulture);
            }
        }
    }
}
